baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "Nodd's Personal Website"
theme = 'papermod'

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]
[params]
  math = true
  homeInfoParams = {Title = "Welcome!", Content = "This is my site for sharing math and other reflections."}
  customCSS = ["css/extended/custom.css"]

[module]
  [[module.imports]]
    path = "github.com/KKKZOZ/hugo-admonitions"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Math"
    url = "/categories/math/"
    weight = 2

  [[menu.main]]
    name = "Physics"
    url = "/categories/physics/"
    weight = 3

  [[menu.main]]
    name = "Others"
    url = "/others/"
    weight = 4